### Should return 200
GET http://localhost:5264/api/catalog HTTP/1.1


### Should return 200
GET http://localhost:5264/api/catalog/2 HTTP/1.1


### Should return 404
GET http://localhost:5264/api/catalog/test HTTP/1.1

### Post a new catalog item
POST http://localhost:5264/api/catalog HTTP/1.1
Content-Type: application/json

{
  "name": "Test",
  "description": "Test description",
  "brand": "Test brand",
  "price": 10.0
}

### POST a new rating 
POST http://localhost:5264/api/catalog/2/ratings HTTP/1.1
Content-Type: application/json

{
  "stars": 3,
  "userName": "Test User",
  "review": "Test review"
}

### PUT an item
PUT http://localhost:5264/api/catalog/2 HTTP/1.1
Content-Type: application/json

{
  "id": 2,
  "name": "New Name",
  "description": "New description",
  "brand": "New brand",
  "price": 120.0
}

### DELETE an item  
DELETE http://localhost:5264/api/catalog/8 HTTP/1.1
